config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  get 'home/index'

  get 'home/authentication'

  devise_for :users
  get 'pages/info'
  get 'test/info'
  resources :users, :only => [:index, :show]

  # root to: redirect('/ideas')
  root to: "ideas#index"
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :user_id, presence: true, uniqueness: true

  def email_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.created_nm = current_user.name

    respond_to do |format|
      if @idea.save
        format.html { redirect_to action: 'new', notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    @idea.updated_nm = current_user.name
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :details, :created_nm, :updated_nm)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @usesr = User.find(params[:id])
  end

  def edit
    @usesr = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Settings", edit_user_registration_path, :class => "navbar-link" %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>
<p>Find me in app/views/home/index.html.erb</p>

app/views/ideas/_form.html.erb
<%= form_for(idea) do |f| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :詳細 %>
    <%= f.text_area :details %>
  </div>

<!--  <div class="field">
    <%= f.label :投稿者 %>
    <%= f.text_field :created_nm %>
  </div>

  <div class="field">
    <%= f.label :更新者 %>
    <%= f.text_field :updated_nm %>
  </div>
-->
  <div class="actions">
    <%= f.submit :新規作成 %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>内容の編集</h1>

<%= render 'form', idea: @idea %>

<%= link_to '表示', @idea %> |
<%= link_to '戻る', ideas_path %>

app/views/ideas/index.html.erb
<h1>伝言メモ</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>投稿者</th>
      <th>投稿日付</th>
      <th>更新者</th>
      <th>更新日付</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.details %></td>
        <td><%= idea.created_nm %></td>
        <td><%= idea.created_at %></td>
        <td><%= idea.updated_nm %></td>
        <td><%= idea.updated_at %></td>
        <td><%= link_to '詳細', idea %></td>
        <td><%= link_to '編集', edit_idea_path(idea) %></td>
        <td><%= link_to '削除', idea, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規', new_idea_path %>

app/views/ideas/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', idea: @idea %>

<%= link_to '戻る', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>詳細:</strong>
  <%= @idea.details %>
</p>

<p>
  <strong>投稿者:</strong>
  <%= @idea.created_nm %>
</p>

<p>
  <strong>更新者:</strong>
  <%= @idea.updated_nm %>
</p>

<%= link_to '編集', edit_idea_path(@idea) %> |
<%= link_to '戻る', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TelmemoApp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">The Idea app</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/ideas">Ideas</a></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        Yoshioka Test 2017
      </div>
    </footer>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/users/edit.html.erb
<h2>ユーザー編集</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<table>
  <thead>
    <tr>
      <th>ユーザーID</th>
      <th>名前</th>
      <th>パスワード</th>
      <th>権限</th>
      <th>更新日</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_id %></td>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td></td>
        <td><%= user.updated_at %></td>
        <td><%= link_to '詳細', user %></td>
        <td><%#= link_to '編集', edit_user_path(user) %></td>
        <td><%= link_to '削除', user, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "サインアップ", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れましたか?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>